################################################################################
##   ____  ____ 
##  /   /\/   / 
## /___/  \  /    Vendor: Xilinx 
## \   \   \/     Version : 2.4
##  \   \         Application : 7 Series FPGAs Transceivers Wizard
##  /   /         Filename : vcs_session.tcl
## /___/   /\     
## \   \  /  \ 
##  \___\/\___\ 
##
##
##
## Script VCS_SESSION.TCL
## Generated by Xilinx 7 Series FPGAs Transceivers Wizard
##
## 
## (c) Copyright 2010-2012 Xilinx, Inc. All rights reserved.
## 
## This file contains confidential and proprietary information
## of Xilinx, Inc. and is protected under U.S. and
## international copyright and other intellectual property
## laws.
## 
## DISCLAIMER
## This disclaimer is not a license and does not grant any
## rights to the materials distributed herewith. Except as
## otherwise provided in a valid license issued to you by
## Xilinx, and to the maximum extent permitted by applicable
## law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
## WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
## AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
## BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
## INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
## (2) Xilinx shall not be liable (whether in contract or tort,
## including negligence, or under any other theory of
## liability) for any loss or damage of any kind or nature
## related to, arising under or in connection with these
## materials, including for any direct, or any indirect,
## special, incidental, or consequential loss or damage
## (including loss of data, profits, goodwill, or any type of
## loss or damage suffered as a result of any action brought
## by a third party) even if such damage or loss was
## reasonably foreseeable or Xilinx had been advised of the
## possibility of the same.
##
## CRITICAL APPLICATIONS
## Xilinx products are not designed or intended to be fail-
## safe, or for use in any application requiring fail-safe
## performance, such as life-support or safety devices or
## systems, Class III medical devices, nuclear facilities,
## applications related to the deployment of airbags, or any
## other applications that could lead to death, personal
## injury, or severe property or environmental damage
## (individually and collectively, "Critical
## Applications"). Customer assumes the sole risk and
## liability of any use of Xilinx products in Critical
## Applications, subject only to applicable laws and
## regulations governing limitations on product liability.
## 
## THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
## PART OF THIS FILE AT ALL TIMES.

  gui_open_window Wave
  gui_sg_create simple_gtx_Group
  gui_list_add_group -id Wave.1 {simple_gtx_Group}

  gui_sg_addsignal -group simple_gtx_Group {{FRAME_CHECK_MODULE}} -divider
  gui_sg_addsignal -group simple_gtx_Group {:simple_gtx_exdes_i:gt0_frame_check:begin_r}
  gui_sg_addsignal -group simple_gtx_Group {:simple_gtx_exdes_i:gt0_frame_check:track_data_r}
  gui_sg_addsignal -group simple_gtx_Group {:simple_gtx_exdes_i:gt0_frame_check:data_error_detected_r}
  gui_sg_addsignal -group simple_gtx_Group {:simple_gtx_exdes_i:gt0_frame_check:start_of_packet_detected_r}
  gui_sg_addsignal -group simple_gtx_Group {:simple_gtx_exdes_i:gt0_frame_check:RX_DATA}
  gui_sg_addsignal -group simple_gtx_Group {:simple_gtx_exdes_i:gt0_frame_check:ERROR_COUNT}
  gui_sg_addsignal -group simple_gtx_Group {{GT0_simple_gtx}} -divider
  gui_sg_addsignal -group simple_gtx_Group {{CPLL Ports}} -divider
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.CPLLFBCLKLOST_OUT}
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.CPLLLOCK_OUT}
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.CPLLLOCKDETCLK_IN}
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.CPLLREFCLKLOST_OUT}
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.CPLLRESET_IN}
  gui_sg_addsignal -group simple_gtx_Group {{Channel - Clocking Ports}} -divider
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.GTREFCLK0_IN}
  gui_sg_addsignal -group simple_gtx_Group {{Channel - DRP Ports }} -divider
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.DRPADDR_IN}
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.DRPCLK_IN}
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.DRPDI_IN}
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.DRPDO_OUT}
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.DRPEN_IN}
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.DRPRDY_OUT}
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.DRPWE_IN}
  gui_sg_addsignal -group simple_gtx_Group {{Clocking Ports}} -divider
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.QPLLCLK_IN}
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.QPLLREFCLK_IN}
  gui_sg_addsignal -group simple_gtx_Group {{RX Initialization and Reset Ports}} -divider
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.RXUSERRDY_IN}
  gui_sg_addsignal -group simple_gtx_Group {{RX Margin Analysis Ports}} -divider
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.EYESCANDATAERROR_OUT}
  gui_sg_addsignal -group simple_gtx_Group {{Receive Ports - CDR Ports}} -divider
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.RXCDRLOCK_OUT}
  gui_sg_addsignal -group simple_gtx_Group {{Receive Ports - FPGA RX Interface Ports}} -divider
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.RXUSRCLK_IN}
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.RXUSRCLK2_IN}
  gui_sg_addsignal -group simple_gtx_Group {{Receive Ports - FPGA RX interface Ports}} -divider
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.RXDATA_OUT}
  gui_sg_addsignal -group simple_gtx_Group {{Receive Ports - RX 8B/10B Decoder Ports}} -divider
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.RXDISPERR_OUT}
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.RXNOTINTABLE_OUT}
  gui_sg_addsignal -group simple_gtx_Group {{Receive Ports - RX AFE}} -divider
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.GTXRXP_IN}
  gui_sg_addsignal -group simple_gtx_Group {{Receive Ports - RX AFE Ports}} -divider
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.GTXRXN_IN}
  gui_sg_addsignal -group simple_gtx_Group {{Receive Ports - RX Buffer Bypass Ports}} -divider
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.RXBUFSTATUS_OUT}
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.RXDLYEN_IN}
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.RXDLYSRESET_IN}
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.RXDLYSRESETDONE_OUT}
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.RXPHALIGN_IN}
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.RXPHALIGNDONE_OUT}
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.RXPHALIGNEN_IN}
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.RXPHDLYRESET_IN}
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.RXPHMONITOR_OUT}
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.RXPHSLIPMONITOR_OUT}
  gui_sg_addsignal -group simple_gtx_Group {{Receive Ports - RX Equalizer Ports}} -divider
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.RXDFEAGCHOLD_IN}
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.RXDFELPMRESET_IN}
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.RXMONITOROUT_OUT}
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.RXMONITORSEL_IN}
  gui_sg_addsignal -group simple_gtx_Group {{Receive Ports - RX Fabric Output Control Ports}} -divider
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.RXOUTCLK_OUT}
  gui_sg_addsignal -group simple_gtx_Group {{Receive Ports - RX Initialization and Reset Ports}} -divider
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.GTRXRESET_IN}
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.RXPMARESET_IN}
  gui_sg_addsignal -group simple_gtx_Group {{Receive Ports - RX8B/10B Decoder Ports}} -divider
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.RXCHARISK_OUT}
  gui_sg_addsignal -group simple_gtx_Group {{Receive Ports -RX Initialization and Reset Ports}} -divider
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.RXRESETDONE_OUT}
  gui_sg_addsignal -group simple_gtx_Group {{TX Initialization and Reset Ports}} -divider
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.GTTXRESET_IN}
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.TXUSERRDY_IN}
  gui_sg_addsignal -group simple_gtx_Group {{Transmit Ports - FPGA TX Interface Ports}} -divider
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.TXUSRCLK_IN}
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.TXUSRCLK2_IN}
  gui_sg_addsignal -group simple_gtx_Group {{Transmit Ports - TX Buffer Bypass Ports}} -divider
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.TXDLYEN_IN}
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.TXDLYSRESET_IN}
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.TXDLYSRESETDONE_OUT}
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.TXPHALIGN_IN}
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.TXPHALIGNDONE_OUT}
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.TXPHALIGNEN_IN}
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.TXPHDLYRESET_IN}
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.TXPHINIT_IN}
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.TXPHINITDONE_OUT}
  gui_sg_addsignal -group simple_gtx_Group {{Transmit Ports - TX Buffer Ports}} -divider
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.TXBUFSTATUS_OUT}
  gui_sg_addsignal -group simple_gtx_Group {{Transmit Ports - TX Data Path interface}} -divider
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.TXDATA_IN}
  gui_sg_addsignal -group simple_gtx_Group {{Transmit Ports - TX Driver and OOB signaling}} -divider
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.GTXTXN_OUT}
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.GTXTXP_OUT}
  gui_sg_addsignal -group simple_gtx_Group {{Transmit Ports - TX Fabric Clock Output Control Ports}} -divider
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.TXOUTCLK_OUT}
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.TXOUTCLKFABRIC_OUT}
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.TXOUTCLKPCS_OUT}
  gui_sg_addsignal -group simple_gtx_Group {{Transmit Ports - TX Gearbox Ports}} -divider
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.TXCHARISK_IN}
  gui_sg_addsignal -group simple_gtx_Group {{Transmit Ports - TX Initialization and Reset Ports}} -divider
  gui_sg_addsignal -group simple_gtx_Group {simple_gtx_TB.simple_gtx_exdes_i.simple_gtx_init_i.simple_gtx_i.gt0_simple_gtx_i.TXRESETDONE_OUT}


  gui_zoom -window Wave.1 -full

