##################################################################################################
## 
##  Xilinx, Inc. 2010            www.xilinx.com 
##  Thu Apr 25 16:21:07 2013
##  Generated by MIG Version 1.8
##  
##################################################################################################
##  File name :       example_top.xdc
##  Details :     Constraints file
##                    FPGA Family:       KINTEX7
##                    FPGA Part:         XC7K160T-FBG484
##                    Speedgrade:        -1
##                    Design Entry:      VHDL
##                    Frequency:         400 MHz
##                    Time Period:       2500 ps
##################################################################################################

##################################################################################################
## Controller 0
## Memory Device: DDR3_SDRAM->Components->MT41J128M8XX-15E
## Data Width: 8
## Time Period: 2500
## Data Mask: 0
##################################################################################################

create_clock -name sys_clk -period 5 [get_ports sys_clk_p]
#set_propagated_clock sys_clk_p
          
############## NET - IOSTANDARD ##################


# PadFunction: IO_L22P_T3_33 
set_property SLEW FAST [get_ports {ddr3_dq[0]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[0]}]
set_property LOC AB13 [get_ports {ddr3_dq[0]}]

# PadFunction: IO_L24N_T3_33 
set_property SLEW FAST [get_ports {ddr3_dq[1]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[1]}]
set_property LOC U13 [get_ports {ddr3_dq[1]}]

# PadFunction: IO_L23N_T3_33 
set_property SLEW FAST [get_ports {ddr3_dq[2]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[2]}]
set_property LOC V12 [get_ports {ddr3_dq[2]}]

# PadFunction: IO_L23P_T3_33 
set_property SLEW FAST [get_ports {ddr3_dq[3]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[3]}]
set_property LOC V13 [get_ports {ddr3_dq[3]}]

# PadFunction: IO_L19P_T3_33 
set_property SLEW FAST [get_ports {ddr3_dq[4]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[4]}]
set_property LOC W12 [get_ports {ddr3_dq[4]}]

# PadFunction: IO_L20N_T3_33 
set_property SLEW FAST [get_ports {ddr3_dq[5]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[5]}]
set_property LOC AB11 [get_ports {ddr3_dq[5]}]

# PadFunction: IO_L22N_T3_33 
set_property SLEW FAST [get_ports {ddr3_dq[6]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[6]}]
set_property LOC AB12 [get_ports {ddr3_dq[6]}]

# PadFunction: IO_L20P_T3_33 
set_property SLEW FAST [get_ports {ddr3_dq[7]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[7]}]
set_property LOC AA11 [get_ports {ddr3_dq[7]}]

# PadFunction: IO_L7P_T1_33 
set_property SLEW FAST [get_ports {ddr3_addr[13]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[13]}]
set_property LOC W6 [get_ports {ddr3_addr[13]}]

# PadFunction: IO_L18P_T2_33 
set_property SLEW FAST [get_ports {ddr3_addr[12]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[12]}]
set_property LOC T9 [get_ports {ddr3_addr[12]}]

# PadFunction: IO_L3N_T0_DQS_33 
set_property SLEW FAST [get_ports {ddr3_addr[11]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[11]}]
set_property LOC AB6 [get_ports {ddr3_addr[11]}]

# PadFunction: IO_L15N_T2_DQS_33 
set_property SLEW FAST [get_ports {ddr3_addr[10]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[10]}]
set_property LOC W10 [get_ports {ddr3_addr[10]}]

# PadFunction: IO_L2N_T0_33 
set_property SLEW FAST [get_ports {ddr3_addr[9]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[9]}]
set_property LOC AB7 [get_ports {ddr3_addr[9]}]

# PadFunction: IO_L1P_T0_33 
set_property SLEW FAST [get_ports {ddr3_addr[8]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[8]}]
set_property LOC AA5 [get_ports {ddr3_addr[8]}]

# PadFunction: IO_L3P_T0_DQS_33 
set_property SLEW FAST [get_ports {ddr3_addr[7]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[7]}]
set_property LOC AA6 [get_ports {ddr3_addr[7]}]

# PadFunction: IO_L10N_T1_33 
set_property SLEW FAST [get_ports {ddr3_addr[6]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[6]}]
set_property LOC U6 [get_ports {ddr3_addr[6]}]

# PadFunction: IO_L10P_T1_33 
set_property SLEW FAST [get_ports {ddr3_addr[5]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[5]}]
set_property LOC U7 [get_ports {ddr3_addr[5]}]

# PadFunction: IO_L11P_T1_SRCC_33 
set_property SLEW FAST [get_ports {ddr3_addr[4]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[4]}]
set_property LOC V7 [get_ports {ddr3_addr[4]}]

# PadFunction: IO_L11N_T1_SRCC_33 
set_property SLEW FAST [get_ports {ddr3_addr[3]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[3]}]
set_property LOC W7 [get_ports {ddr3_addr[3]}]

# PadFunction: IO_L2P_T0_33 
set_property SLEW FAST [get_ports {ddr3_addr[2]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[2]}]
set_property LOC AB8 [get_ports {ddr3_addr[2]}]

# PadFunction: IO_L18N_T2_33 
set_property SLEW FAST [get_ports {ddr3_addr[1]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[1]}]
set_property LOC T8 [get_ports {ddr3_addr[1]}]

# PadFunction: IO_L14N_T2_SRCC_33 
set_property SLEW FAST [get_ports {ddr3_addr[0]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[0]}]
set_property LOC V9 [get_ports {ddr3_addr[0]}]

# PadFunction: IO_L13N_T2_MRCC_33 
set_property SLEW FAST [get_ports {ddr3_ba[2]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_ba[2]}]
set_property LOC Y9 [get_ports {ddr3_ba[2]}]

# PadFunction: IO_L14P_T2_SRCC_33 
set_property SLEW FAST [get_ports {ddr3_ba[1]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_ba[1]}]
set_property LOC U10 [get_ports {ddr3_ba[1]}]

# PadFunction: IO_L9P_T1_DQS_33 
set_property SLEW FAST [get_ports {ddr3_ba[0]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_ba[0]}]
set_property LOC U8 [get_ports {ddr3_ba[0]}]

# PadFunction: IO_L4N_T0_33 
set_property SLEW FAST [get_ports {ddr3_ras_n}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_ras_n}]
set_property LOC AB10 [get_ports {ddr3_ras_n}]

# PadFunction: IO_L4P_T0_33 
set_property SLEW FAST [get_ports {ddr3_cas_n}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_cas_n}]
set_property LOC AA10 [get_ports {ddr3_cas_n}]

# PadFunction: IO_L9N_T1_DQS_33 
set_property SLEW FAST [get_ports {ddr3_we_n}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_we_n}]
set_property LOC V8 [get_ports {ddr3_we_n}]

# PadFunction: IO_L7N_T1_33 
set_property SLEW FAST [get_ports {ddr3_reset_n}]
set_property IOSTANDARD LVCMOS15 [get_ports {ddr3_reset_n}]
set_property LOC Y6 [get_ports {ddr3_reset_n}]

# PadFunction: IO_L13P_T2_MRCC_33 
set_property SLEW FAST [get_ports {ddr3_cke[0]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_cke[0]}]
set_property LOC W9 [get_ports {ddr3_cke[0]}]

# PadFunction: IO_L6N_T0_VREF_33 
set_property SLEW FAST [get_ports {ddr3_odt[0]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_odt[0]}]
set_property LOC Y11 [get_ports {ddr3_odt[0]}]

# PadFunction: IO_L12P_T1_MRCC_33 
set_property IOSTANDARD DIFF_SSTL15 [get_ports {sys_clk_p}]
set_property LOC Y8 [get_ports {sys_clk_p}]

# PadFunction: IO_L12N_T1_MRCC_33 
set_property IOSTANDARD DIFF_SSTL15 [get_ports {sys_clk_n}]
set_property LOC Y7 [get_ports {sys_clk_n}]

# PadFunction: IO_L21P_T3_DQS_33 
set_property SLEW FAST [get_ports {ddr3_dqs_p[0]}]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_p[0]}]
set_property LOC Y13 [get_ports {ddr3_dqs_p[0]}]

# PadFunction: IO_L21N_T3_DQS_33 
set_property SLEW FAST [get_ports {ddr3_dqs_n[0]}]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_n[0]}]
set_property LOC AA13 [get_ports {ddr3_dqs_n[0]}]

# PadFunction: IO_L5P_T0_33 
set_property SLEW FAST [get_ports {ddr3_ck_p[0]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {ddr3_ck_p[0]}]
set_property LOC AA9 [get_ports {ddr3_ck_p[0]}]

# PadFunction: IO_L5N_T0_33 
set_property SLEW FAST [get_ports {ddr3_ck_n[0]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {ddr3_ck_n[0]}]
set_property LOC AA8 [get_ports {ddr3_ck_n[0]}]


set_property INTERNAL_VREF  0.750 [get_iobanks 33]

set_property LOC PHASER_OUT_PHY_X1Y7 [get_cells u_MZDDR3/u_mig_7series_v1_8_memc_ui_top_std/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out]
set_property LOC PHASER_OUT_PHY_X1Y6 [get_cells u_MZDDR3/u_mig_7series_v1_8_memc_ui_top_std/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out]
set_property LOC PHASER_OUT_PHY_X1Y5 [get_cells u_MZDDR3/u_mig_7series_v1_8_memc_ui_top_std/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out]
set_property LOC PHASER_OUT_PHY_X1Y4 [get_cells u_MZDDR3/u_mig_7series_v1_8_memc_ui_top_std/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_out]

## set_property LOC PHASER_IN_PHY_X1Y7 [get_cells u_MZDDR3/u_mig_7series_v1_8_memc_ui_top_std/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_in_gen.phaser_in]
## set_property LOC PHASER_IN_PHY_X1Y6 [get_cells u_MZDDR3/u_mig_7series_v1_8_memc_ui_top_std/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_in_gen.phaser_in]
## set_property LOC PHASER_IN_PHY_X1Y5 [get_cells u_MZDDR3/u_mig_7series_v1_8_memc_ui_top_std/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_in_gen.phaser_in]
set_property LOC PHASER_IN_PHY_X1Y4 [get_cells u_MZDDR3/u_mig_7series_v1_8_memc_ui_top_std/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_in_gen.phaser_in]



set_property LOC OUT_FIFO_X1Y7 [get_cells u_MZDDR3/u_mig_7series_v1_8_memc_ui_top_std/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo]
set_property LOC OUT_FIFO_X1Y6 [get_cells u_MZDDR3/u_mig_7series_v1_8_memc_ui_top_std/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo]
set_property LOC OUT_FIFO_X1Y5 [get_cells u_MZDDR3/u_mig_7series_v1_8_memc_ui_top_std/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo]
set_property LOC OUT_FIFO_X1Y4 [get_cells u_MZDDR3/u_mig_7series_v1_8_memc_ui_top_std/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/out_fifo]

set_property LOC IN_FIFO_X1Y4 [get_cells u_MZDDR3/u_mig_7series_v1_8_memc_ui_top_std/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/in_fifo_gen.in_fifo]

set_property LOC PHY_CONTROL_X1Y1 [get_cells u_MZDDR3/u_mig_7series_v1_8_memc_ui_top_std/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_0.u_ddr_phy_4lanes/phy_control_i]

set_property LOC PHASER_REF_X1Y1 [get_cells u_MZDDR3/u_mig_7series_v1_8_memc_ui_top_std/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_0.u_ddr_phy_4lanes/phaser_ref_i]

set_property LOC OLOGIC_X1Y57 [get_cells u_MZDDR3/u_mig_7series_v1_8_memc_ui_top_std/mem_intfc0/ddr_phy_top0/u_ddr_mc_phy_wrapper/u_ddr_mc_phy/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/ddr_byte_group_io/*slave_ts]

set_property LOC PLLE2_ADV_X1Y1 [get_cells u_MZDDR3/u_ddr3_infrastructure/plle2_i]
set_property LOC MMCME2_ADV_X1Y1 [get_cells u_MZDDR3/u_ddr3_infrastructure/mmcm_i]


set_multicycle_path -from [get_cells -hier -filter {NAME =~ */mc0/mc_read_idle_r_reg}] \
                    -to   [get_cells -hier -filter {NAME =~ */input_[?].iserdes_dq_.iserdesdq}] \
                    -setup 6

set_multicycle_path -from [get_cells -hier -filter {NAME =~ */mc0/mc_read_idle_r_reg}] \
                    -to   [get_cells -hier -filter {NAME =~ */input_[?].iserdes_dq_.iserdesdq}] \
                    -hold 5

set_false_path -through [get_pins -filter {NAME =~ */DQSFOUND} -of [get_cells -hier -filter {REF_NAME == PHASER_IN_PHY}]]

set_multicycle_path -through [get_pins -filter {NAME =~ */OSERDESRST} -of [get_cells -hier -filter {REF_NAME == PHASER_OUT_PHY}]] -setup 2 -start
set_multicycle_path -through [get_pins -filter {NAME =~ */OSERDESRST} -of [get_cells -hier -filter {REF_NAME == PHASER_OUT_PHY}]] -hold 1 -start

set_multicycle_path -to   [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_mig_7series_v1_8_tempmon/device_temp_sync_r1*}] \
                    -setup 12 -end

set_multicycle_path -to   [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_mig_7series_v1_8_tempmon/device_temp_sync_r1*}] \
                    -hold 11 -end
          
set_multicycle_path -to   [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_mig_7series_v1_8_tempmon/xadc_supplied_temperature.rst_r1*}] \
                    -setup 2 -end

set_multicycle_path -to   [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_mig_7series_v1_8_tempmon/xadc_supplied_temperature.rst_r1*}] \
                    -hold 1 -end