project new test.xise

project set "Device Family" "kintex7"

project set "Device" "xc7k160t"

project set "Package" "fbg484"

project set "Speed Grade" "-1"

project set "Synthesis Tool" "XST (VHDL/Verilog)"

project set "Simulator" "Modelsim-SE Mixed"

xfile add "../rtl/traffic_gen/mig_7series_v1_8_afifo.v"
xfile add "../rtl/traffic_gen/mig_7series_v1_8_cmd_gen.v"
xfile add "../rtl/traffic_gen/mig_7series_v1_8_cmd_prbs_gen.v"
xfile add "../rtl/traffic_gen/mig_7series_v1_8_data_prbs_gen.v"
xfile add "../rtl/traffic_gen/mig_7series_v1_8_init_mem_pattern_ctr.v"
xfile add "../rtl/traffic_gen/mig_7series_v1_8_memc_flow_vcontrol.v"
xfile add "../rtl/traffic_gen/mig_7series_v1_8_memc_traffic_gen.v"
xfile add "../rtl/traffic_gen/mig_7series_v1_8_rd_data_gen.v"
xfile add "../rtl/traffic_gen/mig_7series_v1_8_read_data_path.v"
xfile add "../rtl/traffic_gen/mig_7series_v1_8_read_posted_fifo.v"
xfile add "../rtl/traffic_gen/mig_7series_v1_8_s7ven_data_gen.v"
xfile add "../rtl/traffic_gen/mig_7series_v1_8_tg_prbs_gen.v"
xfile add "../rtl/traffic_gen/mig_7series_v1_8_tg_status.v"
xfile add "../rtl/traffic_gen/mig_7series_v1_8_traffic_gen_top.v"
xfile add "../rtl/traffic_gen/mig_7series_v1_8_vio_init_pattern_bram.v"
xfile add "../rtl/traffic_gen/mig_7series_v1_8_wr_data_gen.v"
xfile add "../rtl/traffic_gen/mig_7series_v1_8_write_data_path.v"
xfile add "../rtl/example_top.vhd"
xfile add "../../user_design/rtl/clocking/mig_7series_v1_8_clk_ibuf.v"
xfile add "../../user_design/rtl/clocking/mig_7series_v1_8_infrastructure.v"
xfile add "../../user_design/rtl/clocking/mig_7series_v1_8_iodelay_ctrl.v"
xfile add "../../user_design/rtl/clocking/mig_7series_v1_8_tempmon.v"
xfile add "../../user_design/rtl/controller/mig_7series_v1_8_arb_mux.v"
xfile add "../../user_design/rtl/controller/mig_7series_v1_8_arb_row_col.v"
xfile add "../../user_design/rtl/controller/mig_7series_v1_8_arb_select.v"
xfile add "../../user_design/rtl/controller/mig_7series_v1_8_bank_cntrl.v"
xfile add "../../user_design/rtl/controller/mig_7series_v1_8_bank_common.v"
xfile add "../../user_design/rtl/controller/mig_7series_v1_8_bank_compare.v"
xfile add "../../user_design/rtl/controller/mig_7series_v1_8_bank_mach.v"
xfile add "../../user_design/rtl/controller/mig_7series_v1_8_bank_queue.v"
xfile add "../../user_design/rtl/controller/mig_7series_v1_8_bank_state.v"
xfile add "../../user_design/rtl/controller/mig_7series_v1_8_col_mach.v"
xfile add "../../user_design/rtl/controller/mig_7series_v1_8_mc.v"
xfile add "../../user_design/rtl/controller/mig_7series_v1_8_rank_cntrl.v"
xfile add "../../user_design/rtl/controller/mig_7series_v1_8_rank_common.v"
xfile add "../../user_design/rtl/controller/mig_7series_v1_8_rank_mach.v"
xfile add "../../user_design/rtl/controller/mig_7series_v1_8_round_robin_arb.v"
xfile add "../../user_design/rtl/ecc/mig_7series_v1_8_ecc_buf.v"
xfile add "../../user_design/rtl/ecc/mig_7series_v1_8_ecc_dec_fix.v"
xfile add "../../user_design/rtl/ecc/mig_7series_v1_8_ecc_gen.v"
xfile add "../../user_design/rtl/ecc/mig_7series_v1_8_ecc_merge_enc.v"
xfile add "../../user_design/rtl/ip_top/mig_7series_v1_8_mem_intfc.v"
xfile add "../../user_design/rtl/ip_top/mig_7series_v1_8_memc_ui_top_std.v"
xfile add "../../user_design/rtl/phy/mig_7series_v1_8_ddr_byte_group_io.v"
xfile add "../../user_design/rtl/phy/mig_7series_v1_8_ddr_byte_lane.v"
xfile add "../../user_design/rtl/phy/mig_7series_v1_8_ddr_calib_top.v"
xfile add "../../user_design/rtl/phy/mig_7series_v1_8_ddr_if_post_fifo.v"
xfile add "../../user_design/rtl/phy/mig_7series_v1_8_ddr_mc_phy.v"
xfile add "../../user_design/rtl/phy/mig_7series_v1_8_ddr_mc_phy_wrapper.v"
xfile add "../../user_design/rtl/phy/mig_7series_v1_8_ddr_of_pre_fifo.v"
xfile add "../../user_design/rtl/phy/mig_7series_v1_8_ddr_phy_4lanes.v"
xfile add "../../user_design/rtl/phy/mig_7series_v1_8_ddr_phy_ck_addr_cmd_delay.v"
xfile add "../../user_design/rtl/phy/mig_7series_v1_8_ddr_phy_dqs_found_cal.v"
xfile add "../../user_design/rtl/phy/mig_7series_v1_8_ddr_phy_dqs_found_cal_hr.v"
xfile add "../../user_design/rtl/phy/mig_7series_v1_8_ddr_phy_init.v"
xfile add "../../user_design/rtl/phy/mig_7series_v1_8_ddr_phy_oclkdelay_cal.v"
xfile add "../../user_design/rtl/phy/mig_7series_v1_8_ddr_phy_prbs_rdlvl.v"
xfile add "../../user_design/rtl/phy/mig_7series_v1_8_ddr_phy_rdlvl.v"
xfile add "../../user_design/rtl/phy/mig_7series_v1_8_ddr_phy_tempmon.v"
xfile add "../../user_design/rtl/phy/mig_7series_v1_8_ddr_phy_top.vhd"
xfile add "../../user_design/rtl/phy/mig_7series_v1_8_ddr_phy_wrcal.v"
xfile add "../../user_design/rtl/phy/mig_7series_v1_8_ddr_phy_wrlvl.v"
xfile add "../../user_design/rtl/phy/mig_7series_v1_8_ddr_prbs_gen.v"
xfile add "../../user_design/rtl/ui/mig_7series_v1_8_ui_cmd.v"
xfile add "../../user_design/rtl/ui/mig_7series_v1_8_ui_rd_data.v"
xfile add "../../user_design/rtl/ui/mig_7series_v1_8_ui_top.v"
xfile add "../../user_design/rtl/ui/mig_7series_v1_8_ui_wr_data.v"
xfile add "../../user_design/rtl/MZDDR3.vhd"

xfile add "example_top.ucf"

project set "Library Search Order" "../synth/example_top.lso" -process "Synthesize - XST"

project close
