################################################################################
##   ____  ____ 
##  /   /\/   / 
## /___/  \  /    Vendor: Xilinx 
## \   \   \/     Version : 2.4
##  \   \         Application : 7 Series FPGAs Transceivers Wizard
##  /   /         Filename : simulate_isim.sh
## /___/   /\     
## \   \  /  \ 
##  \___\/\___\ 
##
##
## Script SIMULATE_ISIM.SH
## Generated by Xilinx 7 Series FPGAs Transceivers Wizard
##
## (c) Copyright 2010-2012 Xilinx, Inc. All rights reserved.
##
## This file contains confidential and proprietary information
## of Xilinx, Inc. and is protected under U.S. and
## international copyright and other intellectual property
## laws.
##
## DISCLAIMER
## This disclaimer is not a license and does not grant any
## rights to the materials distributed herewith. Except as
## otherwise provided in a valid license issued to you by
## Xilinx, and to the maximum extent permitted by applicable
## law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
## WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
## AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
## BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
## INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
## (2) Xilinx shall not be liable (whether in contract or tort,
## including negligence, or under any other theory of
## liability) for any loss or damage of any kind or nature
## related to, arising under or in connection with these
## materials, including for any direct, or any indirect,
## special, incidental, or consequential loss or damage
## (including loss of data, profits, goodwill, or any type of
## loss or damage suffered as a result of any action brought
## by a third party) even if such damage or loss was
## reasonably foreseeable or Xilinx had been advised of the
## possibility of the same.
##
## CRITICAL APPLICATIONS
## Xilinx products are not designed or intended to be fail-
## safe, or for use in any application requiring fail-safe
## performance, such as life-support or safety devices or
## systems, Class III medical devices, nuclear facilities,
## applications related to the deployment of airbags, or any
## other applications that could lead to death, personal
## injury, or severe property or environmental damage
## (individually and collectively, "Critical
## Applications"). Customer assumes the sole risk and
## liability of any use of Xilinx products in Critical
## Applications, subject only to applicable laws and
## regulations governing limitations on product liability.
## 
## THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
## PART OF THIS FILE AT ALL TIMES.


##***************************** Beginning of Script ***************************
        
## Create and map work directory
mkdir work

##Multi GT Wrapper
vhpcomp -work work  ../../../gbe.vhd;
##GT Wrapper
vhpcomp -work work  ../../../gbe_gt.vhd;

vhpcomp -work work  ../../example_design/gbe_init.vhd;
vhpcomp -work work  ../../example_design/gbe_adapt_starter.vhd;
vhpcomp -work work  ../../example_design/gbe_agc_loop_fsm.vhd;
vhpcomp -work work  ../../example_design/gbe_ctle_agc_comp.vhd;
vhpcomp -work work  ../../example_design/gbe_adapt_top_dfe.vhd;
vhpcomp -work work  ../../example_design/gbe_lpm_loop_fsm.vhd;
vhpcomp -work work  ../../example_design/gbe_adapt_top_lpm.vhd;
vhpcomp -work work  ../../example_design/gbe_tx_startup_fsm.vhd;
vhpcomp -work work  ../../example_design/gbe_rx_startup_fsm.vhd;
vhpcomp -work work  ../../example_design/gbe_recclk_monitor.vhd;





##Clock Module
vhpcomp -work work  ../../example_design/gbe_gt_usrclk_source.vhd;



##Example Design modules
vhpcomp -work work  ../../example_design/gbe_gt_frame_gen.vhd;
vhpcomp -work work  ../../example_design/gbe_gt_frame_check.vhd;
vhpcomp -work work  ../../example_design/gbe_exdes.vhd;





vhpcomp -work work  ../gbe_tb.vhd;

##Other modules
vhpcomp -work work ../sim_reset_gt_model.vhd;

##Load Design
fuse work.gbe_TB -L unisim -L secureip -o gbe_tb.exe

./gbe_tb.exe -gui -tclbatch wave_isim.tcl -wdb wave_isim  

