################################################################################
##   ____  ____
##  /   /\/   /
## /___/  \  /    Vendor: Xilinx
## \   \   \/     Version : 1.05
##  \   \         Application : ILA v1.05_a Core
##  /   /         Filename : rdi_implement.tcl
## /___/   /\     
## \   \  /  \
##  \___\/\___\
##
##
## rdi_implement.tcl script 
## Generated by Xilinx ILA v1.05_a Core
##
#-----------------------------------------------------------------------------
# Script to synthesize and implement the RTL provided for the ICON core in RDI flow
#-----------------------------------------------------------------------------
create_project -force project_1 {project_1} -part xc7k160tfbg484-1
add_files -norecurse -scan_for_includes {../../chipscope_ila.ngc}
add_files -norecurse {../example_design/example_chipscope_ila.vhd}
set_property top example_chipscope_ila [current_fileset]
import_ip -file {chipscope_icon.xco} -name chipscope_icon
generate_target { all } [get_ips chipscope_icon]
set_property target_constrs_file {../example_design/example_chipscope_ila.xdc} [current_fileset -constrset]
read_xdc -cell ILA_inst ../../chipscope_ila.constraints/chipscope_ila.xdc
synth_design
place_design
route_design
write_bitstream -bitgen_options -w example_design.bit
