

################################################################################
##   ____  ____
##  /   /\/   /
## /___/  \  /    Vendor: Xilinx
## \   \   \/     Version : 2.4
##  \   \         Application : 7 Series FPGAs Transceivers Wizard
##  /   /         Filename : vivado_rdn.tcl 
## /___/   /\     
## \   \  /  \
##  \___\/\___\
##
##
## vivado_rdn.tcl script 
## Generated by Xilinx 7 Series FPGAs Transceivers Wizard
##
##
## (c) Copyright 2010-2012 Xilinx, Inc. All rights reserved.
##
## This file contains confidential and proprietary information
## of Xilinx, Inc. and is protected under U.S. and
## international copyright and other intellectual property
## laws.
##
## DISCLAIMER
## This disclaimer is not a license and does not grant any
## rights to the materials distributed herewith. Except as
## otherwise provided in a valid license issued to you by
## Xilinx, and to the maximum extent permitted by applicable
## law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
## WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
## AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
## BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
## INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
## (2) Xilinx shall not be liable (whether in contract or tort,
## including negligence, or under any other theory of
## liability) for any loss or damage of any kind or nature
## related to, arising under or in connection with these
## materials, including for any direct, or any indirect,
## special, incidental, or consequential loss or damage
## (including loss of data, profits, goodwill, or any type of
## loss or damage suffered as a result of any action brought
## by a third party) even if such damage or loss was
## reasonably foreseeable or Xilinx had been advised of the
## possibility of the same.
##
## CRITICAL APPLICATIONS
## Xilinx products are not designed or intended to be fail-
## safe, or for use in any application requiring fail-safe
## performance, such as life-support or safety devices or
## systems, Class III medical devices, nuclear facilities,
## applications related to the deployment of airbags, or any
## other applications that could lead to death, personal
## injury, or severe property or environmental damage
## (individually and collectively, "Critical
## Applications"). Customer assumes the sole risk and
## liability of any use of Xilinx products in Critical
## Applications, subject only to applicable laws and
## regulations governing limitations on product liability.
## 
## THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
## PART OF THIS FILE AT ALL TIMES.
##
##
################################################################################

## Environment Setup
set device   xc7k160t-fbg484-1
set projName gbe
set design   gbe
set projDir  [file dirname [info script]]
create_project $projName $projDir/results/$projName -part $device -force 
set top_module  gbe_exdes

## Set the Top module
set_property top $top_module [get_property srcset [current_run]]
set_property design_mode RTL [get_filesets sources_1]

## Source Files
add_files -norecurse ../../example_design/gbe_init.vhd
add_files -norecurse ../../example_design/gbe_adapt_starter.vhd
add_files -norecurse ../../example_design/gbe_agc_loop_fsm.vhd
add_files -norecurse ../../example_design/gbe_ctle_agc_comp.vhd
add_files -norecurse ../../example_design/gbe_adapt_top_dfe.vhd
add_files -norecurse ../../example_design/gbe_lpm_loop_fsm.vhd
add_files -norecurse ../../example_design/gbe_adapt_top_lpm.vhd
add_files -norecurse  ../../example_design/gbe_tx_startup_fsm.vhd
add_files -norecurse  ../../example_design/gbe_rx_startup_fsm.vhd
add_files -norecurse  ../../example_design/gbe_recclk_monitor.vhd

add_files -norecurse ../../example_design/gbe_gt_usrclk_source.vhd    
add_files -norecurse ../../example_design/gbe_gt_frame_gen.vhd
add_files -norecurse ../../example_design/gbe_gt_frame_check.vhd
add_files -norecurse ../../../gbe_gt.vhd
add_files -norecurse ../../../gbe.vhd
add_files -norecurse ../../example_design/gbe_exdes.vhd

## Test Files
import_files -fileset [get_filesets sources_1] -force -norecurse ../../simulation/functional/gt_rom_init_rx.dat
import_files -fileset [get_filesets sources_1] -force -norecurse ../../simulation/functional/gt_rom_init_tx.dat

open_rtl_design -part $device
## Read IP level XDC file
read_xdc -cell [get_cells -hier gbe_i] ../../../gbe.xdc

## Read Example Design XDC file
import_files -fileset [get_filesets constrs_1] -force -norecurse ../../example_design/gbe_exdes.xdc

## NGC Files
add_files -norecurse $projDir/../example_design/ila.ngc
add_files -norecurse $projDir/../example_design/icon.ngc
add_files -norecurse $projDir/../example_design/data_vio.ngc
add_files -norecurse $projDir/../example_design/chipscope_ila.ngc
add_files -norecurse $projDir/../example_design/chipscope_icon.ngc
add_files -norecurse $projDir/../example_design/chipscope_vio.ngc

## Run Synthesis
synth_design

## Run Design Optimization 
opt_design

## Run Placement
place_design

## Run Routing
route_design
set_property BITSTREAM.General.UnconstrainedPins {Allow} [current_design]
set_param sta.dlyMediator true

## Generate post-par netlist and sdf file
write_sdf -rename_top_module $top_module -file routed.sdf    
write_vhdl routed.vhd

## Run Timing Analysis 
report_timing -nworst 100 -path_type full -file routed.twr

## Run Design Rule Checks 
report_drc -file report.drc

## Run bitstream
write_bitstream -bitgen_options {-g UnconstrainedPins:Allow} -file routed.bit

exit
## End
